import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import MobileShell from "@/components/MobileShell";
import TopBar from "@/components/TopBar";
import BottomNav from "@/components/BottomNav";
import ContextBar, { ContextBarProps } from "@/components/ContextBar";
import OfferCard, { OfferCardProps, OfferState } from "@/components/OfferCard";

interface Scenario {
  context: ContextBarProps;
  offer: Omit<OfferCardProps, "state" | "onAccept" | "onDismiss">;
}

const scenarios: Scenario[] = [
  {
    context: {
      weather: { temp: "11°C", condition: "rain", description: "Light rain" },
      timeSlot: "lunch",
      merchantSignal: { name: "Café Müller", status: "quiet", txLastHour: 3, avgTx: 12 },
      nearbyEvent: null,
      explanation:
        "It is raining and 11°C outside. You are in the lunch window. Café Müller has had only 3 transactions in the last hour versus their usual 12. This combination triggered a warm drink offer.",
      currentTime: "12:34",
    },
    offer: {
      headline: "Cold outside? Your coffee is waiting.",
      merchant: "Café Müller",
      distance: "80m",
      discount: "15% off",
      expiryMinutes: 12,
      temp: "11°C",
      weatherType: "rain",
      timeAgo: "Just now",
    },
  },
  {
    context: {
      weather: { temp: "22°C", condition: "sun", description: "Sunny" },
      timeSlot: "morning",
      merchantSignal: { name: "Bäckerei Becker", status: "quiet", txLastHour: 5, avgTx: 20 },
      nearbyEvent: null,
      explanation:
        "Sunny morning but Bäckerei Becker is unusually quiet. Only 5 transactions versus usual 20. A breakfast offer was generated to fill their morning slow period.",
      currentTime: "09:15",
    },
    offer: {
      headline: "Skip the queue. Lunch is on us.",
      merchant: "Bäckerei Becker",
      distance: "120m",
      discount: "10% off",
      expiryMinutes: 8,
      temp: "22°C",
      weatherType: "sun",
      timeAgo: "1 min ago",
    },
  },
  {
    context: {
      weather: { temp: "17°C", condition: "cloud", description: "Partly cloudy" },
      timeSlot: "evening",
      merchantSignal: { name: "Pizzeria Napoli", status: "normal", txLastHour: 11, avgTx: 10 },
      nearbyEvent: "Marktplatz Open Air Concert",
      explanation:
        "There is a concert at Marktplatz tonight and Pizzeria Napoli is 200m away. Evening timing plus event proximity triggered a pre-concert dinner offer.",
      currentTime: "19:10",
    },
    offer: {
      headline: "Concert tonight. Grab a bite first.",
      merchant: "Pizzeria Napoli",
      distance: "200m",
      discount: "20% off",
      expiryMinutes: 20,
      temp: "17°C",
      weatherType: "cloud",
      timeAgo: "5 min ago",
    },
  },
];

const Index = () => {
  const navigate = useNavigate();
  const [scenarioIdx, setScenarioIdx] = useState(0);
  const [cardState, setCardState] = useState<OfferState>("active");

  const scenario = scenarios[scenarioIdx];

  useEffect(() => {
    const t = setTimeout(() => {
      toast("Weather update: now 9°C · New offer available", {
        duration: 4000,
        className:
          "!bg-brand-purple !text-white !border-brand-purple [&_*]:!text-white",
      });
    }, 10000);
    return () => clearTimeout(t);
  }, []);

  const cycleScenario = () => {
    setScenarioIdx((i) => (i + 1) % scenarios.length);
    setCardState("active");
  };

  return (
    <MobileShell>
      <TopBar />
      <main className="px-4 pb-28 flex flex-col gap-5 animate-fade-in">
        <ContextBar {...scenario.context} />

        <OfferCard
          {...scenario.offer}
          state={cardState}
          onAccept={() => navigate("/redeem")}
          onDismiss={() => setCardState("dismissed")}
        />

        <p className="text-[12px] text-[#9CA3AF] text-center">
          Offer generated by AI · Just now
        </p>
      </main>

      <button
        onClick={cycleScenario}
        className="fixed bottom-24 right-4 z-50 px-3 py-2 rounded-full bg-[#374151] text-white text-[12px] hover:opacity-90 transition"
        aria-label="Switch scenario (demo)"
      >
        Switch scenario
      </button>

      <BottomNav />
    </MobileShell>
  );
};

export default Index;
